bootloader: fix build with CONFIG_CONSOLE_UART_NONE
Setting CONFIG_CONSOLE_UART_NONE would trigger the following error:

ESP8266_RTOS_SDK/components/bootloader_support/src/bootloader_init.c: In function 'uart_console_configure':
ESP8266_RTOS_SDK/components/bootloader_support/src/bootloader_init.c:628:80:
  error: 'CONFIG_ESP_CONSOLE_UART_BAUDRATE' undeclared (first use in this function); did you mean 'CONFIG_ESP_CONSOLE_UART_NUM'?
     uart_div_modify(CONFIG_ESP_CONSOLE_UART_NUM, BOOTLOADER_CONSOLE_CLK_FREQ / CONFIG_ESP_CONSOLE_UART_BAUDRATE);
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                CONFIG_ESP_CONSOLE_UART_NUM

This is because ESP8266_MODIFY_UART_BAUDRATE is unconditionally defined,
even when CONFIG_CONSOLE_UART_NONE is set. This commit fixes this.